"""Session titles, kept edits, and the auto-save preference

Revision ID: 1d6c295f4a96
Revises: 478a9839faa7
Create Date: 2026-09-07 23:32:35.108360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6c295f4a96'
down_revision: Union[str, Sequence[str], None] = '478a9839faa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caption_sessions', sa.Column('title', sa.String(length=120), nullable=True))
    op.add_column('caption_sessions', sa.Column('edited_text', sa.Text(), nullable=True))
    # server_default, not just a Python-side default: without it this
    # fails on any table that already has rows, which is every
    # deployment and none of the tests.
    op.add_column(
        'users',
        sa.Column(
            'auto_save',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('true'),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auto_save')
    op.drop_column('caption_sessions', 'edited_text')
    op.drop_column('caption_sessions', 'title')
    # ### end Alembic commands ###
