"""guide session titles

Revision ID: 4cdf56985620
Revises: 1d6c295f4a96
Create Date: 2026-09-08 11:32:08.408788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cdf56985620'
down_revision: Union[str, Sequence[str], None] = '1d6c295f4a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guide_sessions', sa.Column('title', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guide_sessions', 'title')
    # ### end Alembic commands ###
